name: Deploy Static App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    # STEP 1️⃣ - Checkout Code
    - uses: actions/checkout@v4

    # STEP 2️⃣ - Login + Build + Push
    - name: Build and Push Docker Image
      run: |
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker build -t chandrulinesmasher/mysampleappv1:latest .
        docker push chandrulinesmasher/mysampleappv1:latest

    # STEP 3️⃣ - SSH and Deploy to EC2
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo docker stop myapp || true
          sudo docker rm myapp || true
          sudo docker pull chandrulinesmasher/mysampleappv1:latest
          sudo docker run -d \
            -p 80:80 \
            --restart always \
            --name myapp \
            chandrulinesmasher/mysampleappv1:latest
