name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Checkout repository
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2️⃣ Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 3️⃣ Login to DockerHub
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 4️⃣ Build and Push Docker Image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: chandrulinesmasher/mysampleappv1:latest

    # 5️⃣ SSH into EC2 and Deploy
    - name: SSH and Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          echo "Stopping existing container..."
          sudo docker stop myapp || true

          echo "Removing old container..."
          sudo docker rm myapp || true

          echo "Pulling latest image..."
          sudo docker pull chandrulinesmasher/mysampleappv1:latest

          echo "Starting new container..."
          sudo docker run -d \
            -p 80:3000 \
            --restart always \
            --name myapp \
            chandrulinesmasher/mysampleappv1:latest

          echo "Deployment completed successfully!"
